version: '3'

services:
  db:
    build: ./services/mongo
    restart: always
    # volumes:
    #   - ./mongo/data:/data/db 
    environment:
      MONGO_INITDB_DATABASE: practica2 

  web:
    build: ./services/prediction_microservice
    restart: always
    ports:
      - 8081:8080
    # volumes:
    #   - ./mongo/data:/data/db 
    depends_on:
      - db
    environment:
      - MONGO_HOST=practica2_db_1
      - MONGO_PORT=27017